/**
 * Compact, model-facing summaries of the landing-page data
 * (site/upstream). Kept to a few KB: no coordinates, sequences only on
 * request and capped.
 */
import type { AfDetails, Citation, PdbDetails } from '../../../site/upstream/types';
import type { PubchemCompound } from '../../../site/upstream/pubchem';
import type { Compound } from '../../../site/dataTypes';
import { shortName } from '../../../site/render/pdbPage';
import { toSentenceCase } from '../../../site/render/sentenceCase';
import { formatMethod, formatRange } from '../../../site/render/format';
import { SITE_ORIGIN } from '../../../site/nav';
import { structurePath } from '../../../site/routes';

const MAX_SEQUENCE = 2000;
const MAX_LIGANDS = 20;
const MAX_ENTITIES = 12;

export function pdbPageUrl(id: string): string {
  return `${SITE_ORIGIN}${structurePath({ kind: 'pdb', id })}`;
}

export function afPageUrl(id: string): string {
  return `${SITE_ORIGIN}${structurePath({ kind: 'af', id })}`;
}

export function compoundPageUrl(c: { slug?: string; cid: number }): string {
  return `${SITE_ORIGIN}${structurePath(c.slug ? { kind: 'compound', slug: c.slug } : { kind: 'cid', cid: c.cid })}`;
}

/** "Oefner C, Suck D (1986) Title. J Mol Biol 192:605-632. doi:..." */
export function formatCitation(c: Citation | undefined): string | undefined {
  if (!c?.title) return undefined;
  const authors = c.authors.length > 3 ? `${c.authors.slice(0, 3).join(', ')} et al.` : c.authors.join(', ');
  const pages = c.pageFirst ? `:${c.pageFirst}${c.pageLast ? `-${c.pageLast}` : ''}` : '';
  const where = [c.journal, c.volume ? `${c.volume}${pages}` : ''].filter(Boolean).join(' ');
  return [
    authors && `${authors}${c.year ? ` (${c.year})` : ''}`,
    c.title.replace(/\.$/, '') + '.',
    where && `${where}.`,
    c.doi && `doi:${c.doi}`,
  ]
    .filter(Boolean)
    .join(' ');
}

/**
 * When the deposited model isn't the whole biological molecule, say so
 * plainly: the viewer shows the deposited chains, and the model otherwise
 * describes "a tetramer" over a picture of two chains (1HHO).
 */
export function assemblyNote(d: Pick<PdbDetails, 'assembly' | 'polymerChainCount'>): string | undefined {
  const deposited = d.polymerChainCount;
  const assembled = d.assembly?.chainCount;
  if (!deposited || !assembled || deposited === assembled) return undefined;
  const what = d.assembly?.oligomericDetails ?? `${assembled}-chain`;
  if (deposited < assembled) {
    return (
      `This entry's file contains ${deposited} of the ${assembled} chains of the biological assembly (${what}); ` +
      `the rest is generated by crystallographic symmetry. The viewer shows the ${deposited} deposited chains, so describe ` +
      `the picture as ${deposited} chains, part of a ${what} molecule.`
    );
  }
  return (
    `This entry's file contains ${deposited} chains, more than the biological assembly (${what}, ${assembled} chains): ` +
    `the crystal holds several copies of the molecule, and the viewer shows all ${deposited} chains.`
  );
}

/**
 * One-paragraph facts for the tool's text content. Models tend to stay silent
 * after a widget renders unless the text gives them something to say, so the
 * essentials go here too, not only in structuredContent.
 */
export function pdbFacts(d: PdbDetails): string {
  const method = d.method ? formatMethod(d.method) : undefined;
  const parts = [
    `${shortName(d)} (PDB ${d.id})`,
    method && (d.resolution ? `${method} at ${d.resolution} Å` : method),
    d.releaseDate && `released ${d.releaseDate.slice(0, 4)}`,
    [...new Set(d.entities.flatMap((e) => e.organisms))].slice(0, 3).join(', ') || undefined,
  ].filter(Boolean);
  const chains = d.entities
    .slice(0, MAX_ENTITIES)
    .map((e) => `${e.description ? toSentenceCase(e.description) : `entity ${e.entityId}`} (chain${e.chainIds.length > 1 ? 's' : ''} ${e.chainIds.join(', ')})`)
    .join('; ');
  const ligands = d.ligands
    .slice(0, 6)
    .map((l) => `${l.id}${l.name ? ` (${toSentenceCase(l.name)})` : ''}${l.instanceCount > 1 ? ` x${l.instanceCount}` : ''}`)
    .join(', ');
  return [
    `${parts.join(', ')}.`,
    d.polymerChainCount ? `${d.polymerChainCount} polymer chain${d.polymerChainCount === 1 ? '' : 's'} in the file: ${chains}.` : chains && `Chains: ${chains}.`,
    ligands && `Ligands: ${ligands}.`,
  ]
    .filter(Boolean)
    .join(' ');
}

export function afFacts(d: AfDetails): string {
  const f = d.plddtFractions;
  return [
    `AlphaFold model of ${d.description ?? d.uniprot?.proteinName ?? d.id}${d.gene ? ` (${d.gene})` : ''}${d.organism ? `, ${d.organism}` : ''}, UniProt ${d.id}`,
    d.sequenceLength && `${d.sequenceLength} residues`,
    d.meanPlddt !== undefined && `mean pLDDT ${d.meanPlddt.toFixed(1)}`,
    f &&
      `${percent(f.veryHigh)}% very high (>90), ${percent(f.confident)}% confident (70-90), ${percent(f.low)}% low (50-70), ${percent(f.veryLow)}% very low (<50, often disordered)`,
  ]
    .filter(Boolean)
    .join(', ')
    .concat('.');
}

export function compoundFacts(c: { name?: string; title?: string; formula?: string; weight?: string; iupac?: string; cid: number }): string {
  const name = c.name ?? c.title ?? `PubChem CID ${c.cid}`;
  return [`${name} (PubChem CID ${c.cid})`, c.formula && `formula ${c.formula}`, c.weight && `${c.weight} g/mol`, c.iupac && `IUPAC name ${c.iupac}`]
    .filter(Boolean)
    .join(', ')
    .concat('.');
}

export function pdbSummary(d: PdbDetails) {
  const ss = d.secondaryStructure;
  return {
    kind: 'pdb' as const,
    id: d.id,
    name: shortName(d),
    title: d.title ? toSentenceCase(d.title) : undefined,
    method: d.method ? formatMethod(d.method) : undefined,
    resolutionAngstrom: d.resolution,
    releaseYear: d.releaseDate ? Number(d.releaseDate.slice(0, 4)) : undefined,
    organisms: [...new Set(d.entities.flatMap((e) => e.organisms))],
    /** Chains in the file, which is what the viewer shows. */
    polymerChainCount: d.polymerChainCount,
    biologicalAssembly: d.assembly
      ? {
          chains: d.assembly.chainCount,
          description: d.assembly.oligomericDetails,
          symmetry: d.assembly.oligomericState,
          stoichiometry: d.assembly.stoichiometry,
        }
      : undefined,
    chainsNote: assemblyNote(d),
    molecularWeightKda: d.molecularWeight,
    entities: d.entities.slice(0, MAX_ENTITIES).map((e) => ({
      description: e.description ? toSentenceCase(e.description) : undefined,
      type: e.type,
      chains: e.chainIds,
      length: e.length,
      uniprot: e.uniprotIds,
    })),
    ligands: d.ligands.slice(0, MAX_LIGANDS).map((l) => ({
      id: l.id,
      name: l.name ? toSentenceCase(l.name) : undefined,
      copies: l.instanceCount,
    })),
    secondaryStructure: ss
      ? {
          helices: ss.chains.reduce((n, c) => n + c.helices.length, 0),
          strands: ss.chains.reduce((n, c) => n + c.strands.length, 0),
        }
      : undefined,
    alphafoldModels: d.alphafoldIds,
    citation: formatCitation(d.citation),
    pageUrl: pdbPageUrl(d.id),
  };
}

function percent(fraction: number): number {
  return Math.round(fraction * 1000) / 10;
}

export function afSummary(d: AfDetails) {
  const f = d.plddtFractions;
  return {
    kind: 'alphafold' as const,
    id: d.id,
    protein: d.description ?? d.uniprot?.proteinName,
    gene: d.gene,
    organism: d.organism,
    sequenceLength: d.sequenceLength,
    meanPlddt: d.meanPlddt,
    confidencePercent: f
      ? { veryHighAbove90: percent(f.veryHigh), confident70to90: percent(f.confident), low50to70: percent(f.low), veryLowBelow50: percent(f.veryLow) }
      : undefined,
    colorKey:
      'AlphaFold DB colors: dark blue = very high (pLDDT > 90), light blue = confident (70-90), yellow = low (50-70), orange = very low (< 50, often disordered).',
    experimentalStructures: d.pdbStructures.slice(0, 8).map((x) => x.id),
    experimentalStructureCount: d.pdbStructureCount,
    citation:
      'Jumper J et al. (2021) Highly accurate protein structure prediction with AlphaFold. Nature 596:583-589; Varadi M et al. AlphaFold Protein Structure Database. Nucleic Acids Res.',
    pageUrl: afPageUrl(d.id),
  };
}

export function compoundSummary(c: Compound | (PubchemCompound & { slug?: string })) {
  const curated = 'name' in c;
  return {
    kind: 'compound' as const,
    cid: c.cid,
    slug: c.slug,
    name: curated ? c.name : c.title,
    formula: c.formula,
    molecularWeight: c.weight ? `${c.weight} g/mol` : undefined,
    iupacName: c.iupac,
    smiles: c.smiles,
    pageUrl: compoundPageUrl(c),
  };
}

export type DetailSection = 'secondaryStructure' | 'sequence' | 'ligands' | 'citation' | 'related';

/** Extra sections for get_structure_details on a PDB entry. */
export function pdbSections(d: PdbDetails, sections: DetailSection[]) {
  const out: Record<string, unknown> = {};
  if (sections.includes('secondaryStructure')) {
    const ss = d.secondaryStructure;
    out.secondaryStructure = ss
      ? {
          source: ss.source === 'pdbe' ? 'PDBe' : 'RCSB',
          numbering:
            ss.numbering === 'author'
              ? 'Author residue numbers, as shown in the PDB file and viewers'
              : 'Sequence positions (label_seq_id), because only the RCSB fallback was available',
          chains: ss.chains.map((c) => ({
            chain: c.chainId,
            helices: c.helices.map(formatRange),
            strands: c.strands.map((s) => (s.sheetId ? `${formatRange(s)} (sheet ${s.sheetId})` : formatRange(s))),
          })),
        }
      : 'Not available: both PDBe and RCSB failed to answer.';
  }
  if (sections.includes('sequence')) {
    out.sequences = d.entities.slice(0, MAX_ENTITIES).map((e) => ({
      description: e.description,
      chains: e.chainIds,
      length: e.length,
      sequence: e.sequence && e.sequence.length > MAX_SEQUENCE ? `${e.sequence.slice(0, MAX_SEQUENCE)}...` : e.sequence,
    }));
  }
  if (sections.includes('ligands')) {
    out.ligands = d.ligands.map((l) => ({
      id: l.id,
      name: l.name ? toSentenceCase(l.name) : undefined,
      formula: l.formula,
      copies: l.instanceCount,
      chains: l.chainIds,
    }));
    out.excludedAdditives = d.excludedLigandIds;
  }
  // `citation` (the formatted string) is already in the summary; this adds the identifiers.
  // It must not reuse the `citation` key: the output schema declares that one as a string.
  if (sections.includes('citation') && d.citation) {
    out.citationIds = { pubmedId: d.citation.pubmedId, doi: d.citation.doi };
  }
  if (sections.includes('related')) {
    out.related = d.related.map((r) => ({
      id: r.id,
      title: r.title ? toSentenceCase(r.title) : undefined,
      method: r.method ? formatMethod(r.method) : undefined,
      resolutionAngstrom: r.resolution,
    }));
  }
  if (d.partial.length) out.unavailableParts = d.partial;
  return out;
}

/** Extra sections for get_structure_details on an AlphaFold model. */
export function afSections(d: AfDetails, sections: DetailSection[]) {
  const out: Record<string, unknown> = {};
  const u = d.uniprot;
  if (u) {
    out.function = u.functionText;
    out.subunit = u.subunit;
    out.subcellularLocations = u.subcellularLocations;
    out.diseases = u.diseases;
  }
  if (sections.includes('related')) {
    out.experimentalStructures = d.pdbStructures.map((x) => ({
      id: x.id,
      method: x.method,
      resolutionAngstrom: x.resolution,
      chains: x.chains,
    }));
  }
  if (sections.includes('secondaryStructure') || sections.includes('ligands')) {
    out.note =
      'AlphaFold models have no deposited secondary structure or ligands. Ask about an experimental PDB entry from experimentalStructures for those.';
  }
  if (d.partial.length) out.unavailableParts = d.partial;
  return out;
}
