/**
 * Curated compound slugs (/compound/caffeine) <-> PubChem CIDs, from the slim
 * map data/compoundSlugs.json (generated by scripts/validate-compounds.ts).
 * Shared by the app, the Pages Functions and the tests.
 *
 * Lets the app give a searched compound its canonical address, and load a
 * /compound/:slug or /embed/compound/:slug page by CID, without a lossy
 * slug-to-name lookup ("1-2-dichloroethane" is not "1,2-dichloroethane").
 */
import slugsByCid from '../data/compoundSlugs.json';

const SLUG_BY_CID = new Map<number, string>(
  Object.entries(slugsByCid as Record<string, string>).map(([cid, slug]) => [Number(cid), slug])
);
const CID_BY_SLUG = new Map<string, number>([...SLUG_BY_CID].map(([cid, slug]) => [slug, cid]));

export function slugForCid(cid: number): string | undefined {
  return SLUG_BY_CID.get(cid);
}

export function cidForSlug(slug: string): number | undefined {
  return CID_BY_SLUG.get(slug);
}
