/**
 * Validate and enrich the small-molecule dataset used for /compound/:slug pages.
 *
 * Usage:
 *   pnpm exec tsx scripts/validate-compounds.ts           # fetch, validate, rewrite data/compounds.json
 *   pnpm exec tsx scripts/validate-compounds.ts --check   # validate only, no writes, exit 1 on problems
 *
 * data/compounds.json holds `{ _comment, compounds: [...] }`. For every entry the
 * hand-edited inputs are `slug`, `cid`, `name` and `category`; everything else
 * (formula, weight, iupac, smiles, synonyms, heavyAtoms) is filled in from
 * PubChem PUG REST by this script. To add a compound, append an entry with just
 * the four input fields and run the script without --check.
 *
 * An entry is kept only if:
 *   - the input fields are valid (kebab-case ASCII slug, positive integer CID,
 *     non-empty name, known category) and the slug and CID are unique;
 *   - PubChem knows the CID;
 *   - the record is a single component (no "." in its SMILES, so no salts or mixtures);
 *   - a 3D conformer exists (GET/HEAD .../cid/{cid}/SDF?record_type=3d returns 200).
 * Entries that fail are dropped with a warning (or reported as problems with --check).
 *
 * --check also reports entries whose stored PubChem-derived fields are missing
 * (a problem) or differ from what PubChem currently returns (a warning only,
 * since PubChem edits synonyms and names over time; re-run without --check to refresh).
 *
 * PubChem usage policy: at most 5 requests/second and 400/minute. Requests are
 * throttled to one start every 250 ms; properties and synonyms are fetched in
 * batches, the 3D check is one request per CID. 429/5xx responses are retried
 * with backoff by scripts/lib/http.ts.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchJson, fetchText, mapLimit, HttpError } from './lib/http';

const DATA_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '../data/compounds.json');
const SLUGS_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '../data/compoundSlugs.json');

/** `{ "2519": "caffeine", ... }`, keyed by CID. Checked against compounds.json by site/build/build.test.ts. */
export function compoundSlugMap(compounds: { slug: string; cid: number }[]): Record<string, string> {
  return Object.fromEntries([...compounds].sort((a, b) => a.slug.localeCompare(b.slug)).map((c) => [String(c.cid), c.slug]));
}
const PUG = 'https://pubchem.ncbi.nlm.nih.gov/rest/pug';
const COMMENT =
  'Generated by scripts/validate-compounds.ts. Edit slug/cid/name/category, then re-run.';

export const CATEGORIES = [
  'common-drugs',
  'school-chemistry',
  'neurotransmitters',
  'vitamins',
  'amino-acids',
  'sugars',
  'hormones',
  'natural-products',
  'stimulants',
  'solvents',
  'fatty-acids-lipids',
  'nucleotides',
  'dyes-pigments',
  'toxins-poisons',
  'food-flavor-fragrance',
] as const;
export type CompoundCategory = (typeof CATEGORIES)[number];

export interface Compound {
  slug: string;
  cid: number;
  name: string;
  category: CompoundCategory;
  formula: string;
  weight: string;
  iupac: string;
  smiles: string;
  synonyms: string[];
  heavyAtoms: number;
}

type InputEntry = Partial<Compound> & Record<string, unknown>;

interface PubChemProperties {
  CID: number;
  MolecularFormula?: string;
  MolecularWeight?: string | number;
  IUPACName?: string;
  SMILES?: string;
  IsomericSMILES?: string;
  CanonicalSMILES?: string;
  ConnectivitySMILES?: string;
  HeavyAtomCount?: number;
}

const PROPERTY_LIST = [
  'MolecularFormula',
  'MolecularWeight',
  'IUPACName',
  'SMILES',
  'IsomericSMILES',
  'CanonicalSMILES',
  'ConnectivitySMILES',
  'HeavyAtomCount',
].join(',');

const PROPERTY_BATCH = 100;
const SYNONYM_BATCH = 50;
const MAX_SYNONYMS = 6;
const MIN_INTERVAL_MS = 250;

// ---------------------------------------------------------------------------
// Rate limiting: every PubChem request goes through `throttled`.
// ---------------------------------------------------------------------------

let nextSlot = 0;
async function throttled<T>(fn: () => Promise<T>): Promise<T> {
  const now = Date.now();
  const start = Math.max(now, nextSlot);
  nextSlot = start + MIN_INTERVAL_MS;
  if (start > now) await new Promise((r) => setTimeout(r, start - now));
  return fn();
}

const getJson = <T>(url: string) => throttled(() => fetchJson<T>(url));

// ---------------------------------------------------------------------------
// PubChem lookups
// ---------------------------------------------------------------------------

async function fetchProperties(cids: number[]): Promise<Map<number, PubChemProperties>> {
  const out = new Map<number, PubChemProperties>();
  const fetchBatch = async (batch: number[]) => {
    const url = `${PUG}/compound/cid/${batch.join(',')}/property/${PROPERTY_LIST}/JSON`;
    const data = await getJson<{ PropertyTable?: { Properties?: PubChemProperties[] } }>(url);
    for (const p of data.PropertyTable?.Properties ?? []) out.set(p.CID, p);
  };
  for (let i = 0; i < cids.length; i += PROPERTY_BATCH) {
    const batch = cids.slice(i, i + PROPERTY_BATCH);
    try {
      await fetchBatch(batch);
    } catch (err) {
      // One bad CID can fail the whole batch: retry one by one.
      if (batch.length === 1) continue;
      console.warn(`  property batch failed (${describe(err)}), retrying individually`);
      for (const cid of batch) {
        try {
          await fetchBatch([cid]);
        } catch {
          /* reported later as "not found" */
        }
      }
    }
  }
  return out;
}

async function fetchSynonyms(cids: number[]): Promise<Map<number, string[]>> {
  const out = new Map<number, string[]>();
  type SynResponse = { InformationList?: { Information?: { CID: number; Synonym?: string[] }[] } };
  const fetchBatch = async (batch: number[]) => {
    const data = await getJson<SynResponse>(`${PUG}/compound/cid/${batch.join(',')}/synonyms/JSON`);
    for (const info of data.InformationList?.Information ?? []) out.set(info.CID, info.Synonym ?? []);
  };
  for (let i = 0; i < cids.length; i += SYNONYM_BATCH) {
    const batch = cids.slice(i, i + SYNONYM_BATCH);
    try {
      await fetchBatch(batch);
    } catch (err) {
      if (batch.length === 1) continue;
      console.warn(`  synonym batch failed (${describe(err)}), retrying individually`);
      for (const cid of batch) {
        try {
          await fetchBatch([cid]);
        } catch {
          out.set(cid, []);
        }
      }
    }
  }
  return out;
}

let headSupported = true;

/** True if PubChem has a 3D conformer SDF for this CID, false on 404. Throws on other errors. */
async function has3dConformer(cid: number): Promise<boolean> {
  const url = `${PUG}/compound/cid/${cid}/SDF?record_type=3d`;
  try {
    if (headSupported) {
      try {
        await throttled(() => fetchText(url, { method: 'HEAD' }));
        return true;
      } catch (err) {
        if (err instanceof HttpError && (err.status === 405 || err.status === 501)) {
          headSupported = false;
        } else {
          throw err;
        }
      }
    }
    await throttled(() => fetchText(url));
    return true;
  } catch (err) {
    if (err instanceof HttpError && err.status === 404) return false;
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Synonym filtering
// ---------------------------------------------------------------------------

const REGISTRY_PATTERNS: RegExp[] = [
  /^\d{2,7}-\d{2}-\d$/, // CAS number
  /^\d+$/, // bare numbers
  /\b(UNII|CHEBI|CHEMBL|SCHEMBL|DTXSID|DTXCID|EINECS|ELINCS|NSC|BRN|HSDB|CCRIS|ZINC|AKOS|MFCD|NCGC|BDBM|RCRA|WLN|Tox21|KBio|BSPBio|SPBio|Prestwick|Spectrum|Lopac|SMR|MLS|NCI|InChI|Epitope)\b/i,
  /^(EC|UN|AI3|CAS|FEMA|INS|E)[ -]?\d/i, // EC 200-362-1, UN 1234, FEMA No. etc.
  /^[A-Za-z]{1,5}[ -]?\d[\d-]*[A-Za-z]?$/, // research codes like "Ro 5-2807", "MK-0869"
];

const SALT_OR_FORM =
  /\b(HCl|HBr|hydrochloride|hydrobromide|mesylate|besylate|maleate|tartrate|succinate|citrate|picrate|sulfate|phosphate salt|sodium|potassium|calcium|magnesium|hydrate|monohydrate|dihydrate|trihydrate|salt|solution|labeled|deuterated|tritiated|radiolabeled|standard|reference|impurity|mixture)\b/i;

export function isReadableSynonym(s: string): boolean {
  const t = s.trim();
  if (t.length < 2 || t.length > 60) return false;
  if (/[[\](){}:;_@#=|\\]/.test(t)) return false; // bracketed tags, database ids, SMILES-like
  // Comma-joined lists ("Cusi, Acetilcolina", "AZD-9291,Osimertinib"); keeps locants like "1,3,7-" and "N,N-".
  if (/,\s|,[A-Za-z]{3}/.test(t)) return false;
  if (!/[a-z]/i.test(t)) return false;
  // All-caps strings: keep short acronyms (ATP, GABA, DMSO), drop codes and shouting duplicates.
  if (!/[a-z]/.test(t) && (/\d/.test(t) || t.length > 6)) return false;
  if (REGISTRY_PATTERNS.some((re) => re.test(t))) return false;
  if (SALT_OR_FORM.test(t)) return false;
  return true;
}

/** Comparison key that treats "Methylene blue" and "methylene-blue" as the same synonym. */
const synonymKey = (s: string) => s.toLowerCase().replace(/[^a-z0-9+]/g, '');

export function pickSynonyms(name: string, raw: string[]): string[] {
  const seen = new Set<string>([synonymKey(name)]);
  const out = [name];
  for (const s of raw) {
    if (out.length >= MAX_SYNONYMS) break;
    const t = s.trim();
    const key = synonymKey(t);
    if (seen.has(key) || !isReadableSynonym(t)) continue;
    seen.add(key);
    out.push(t);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const DERIVED_FIELDS = ['formula', 'weight', 'iupac', 'smiles', 'synonyms', 'heavyAtoms'] as const;

function describe(err: unknown): string {
  if (err instanceof HttpError) return `HTTP ${err.status}`;
  return err instanceof Error ? err.message : String(err);
}

function pickSmiles(p: PubChemProperties): string | undefined {
  return p.SMILES ?? p.IsomericSMILES ?? p.CanonicalSMILES ?? p.ConnectivitySMILES;
}

function inputProblems(e: InputEntry): string[] {
  const problems: string[] = [];
  if (typeof e.slug !== 'string' || !SLUG_RE.test(e.slug)) problems.push(`invalid slug ${JSON.stringify(e.slug)}`);
  if (typeof e.cid !== 'number' || !Number.isInteger(e.cid) || e.cid <= 0) problems.push(`invalid cid ${JSON.stringify(e.cid)}`);
  if (typeof e.name !== 'string' || !e.name.trim()) problems.push('missing name');
  if (!CATEGORIES.includes(e.category as CompoundCategory)) problems.push(`unknown category ${JSON.stringify(e.category)}`);
  return problems;
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const file = JSON.parse(readFileSync(DATA_PATH, 'utf8')) as { compounds?: InputEntry[] };
  const entries = file.compounds ?? [];
  const problems: string[] = [];
  const warnings: string[] = [];
  const dropped: { label: string; reason: string }[] = [];
  const drop = (e: InputEntry, reason: string) => dropped.push({ label: `${e.slug ?? '?'} (cid ${e.cid ?? '?'})`, reason });

  console.log(`Loaded ${entries.length} entries from ${DATA_PATH}`);

  // 1. Input fields, slug and CID uniqueness.
  const seenSlugs = new Map<string, number>();
  const seenCids = new Map<number, string>();
  const candidates: InputEntry[] = [];
  for (const e of entries) {
    const bad = inputProblems(e);
    if (bad.length) {
      drop(e, bad.join(', '));
      continue;
    }
    const slug = e.slug as string;
    const cid = e.cid as number;
    if (seenSlugs.has(slug)) {
      drop(e, `duplicate slug "${slug}"`);
      continue;
    }
    if (seenCids.has(cid)) {
      drop(e, `duplicate cid, already used by "${seenCids.get(cid)}"`);
      continue;
    }
    seenSlugs.set(slug, cid);
    seenCids.set(cid, slug);
    candidates.push(e);
  }

  // 2. Properties and synonyms (batched).
  const cids = candidates.map((e) => e.cid as number);
  console.log(`Fetching properties for ${cids.length} CIDs...`);
  const props = await fetchProperties(cids);
  console.log(`Fetching synonyms...`);
  const synonyms = await fetchSynonyms(cids);

  // 3. Single component + 3D conformer (one request per CID).
  const singleComponent = candidates.filter((e) => {
    const p = props.get(e.cid as number);
    const smiles = p && pickSmiles(p);
    if (!p || !smiles) {
      drop(e, 'CID not found on PubChem (no properties)');
      return false;
    }
    if (smiles.includes('.')) {
      drop(e, `multi-component record (salt or mixture): ${smiles}`);
      return false;
    }
    return true;
  });

  console.log(`Checking 3D conformers for ${singleComponent.length} CIDs...`);
  let done = 0;
  const conformer = await mapLimit(singleComponent, 5, async (e) => {
    let result: boolean | Error;
    try {
      result = await has3dConformer(e.cid as number);
    } catch (err) {
      result = new Error(describe(err));
    }
    if (++done % 100 === 0) console.log(`  ${done}/${singleComponent.length}`);
    return result;
  });

  // 4. Build the output entries.
  const kept: Compound[] = [];
  singleComponent.forEach((e, i) => {
    const ok = conformer[i];
    if (ok instanceof Error) {
      drop(e, `3D check failed: ${ok.message}`);
      return;
    }
    if (!ok) {
      drop(e, 'no 3D conformer on PubChem');
      return;
    }
    const p = props.get(e.cid as number)!;
    const name = (e.name as string).trim();
    const fresh: Compound = {
      slug: e.slug as string,
      cid: e.cid as number,
      name,
      category: e.category as CompoundCategory,
      formula: p.MolecularFormula ?? '',
      weight: p.MolecularWeight === undefined ? '' : String(p.MolecularWeight),
      iupac: p.IUPACName ?? '',
      smiles: pickSmiles(p)!,
      synonyms: pickSynonyms(name, synonyms.get(e.cid as number) ?? []),
      heavyAtoms: p.HeavyAtomCount ?? 0,
    };
    if (!fresh.formula || !fresh.weight || !fresh.heavyAtoms) {
      drop(e, 'incomplete PubChem properties');
      return;
    }
    if (!fresh.iupac) warnings.push(`${fresh.slug}: PubChem has no IUPAC name`);

    if (checkOnly) {
      const missing = DERIVED_FIELDS.filter((f) => e[f] === undefined || e[f] === '');
      if (missing.length) {
        problems.push(`${fresh.slug}: missing ${missing.join(', ')} (run without --check to fill)`);
      } else {
        const stale = DERIVED_FIELDS.filter((f) => JSON.stringify(e[f]) !== JSON.stringify(fresh[f]));
        if (stale.length) warnings.push(`${fresh.slug}: ${stale.join(', ')} differ from PubChem (run without --check to refresh)`);
      }
    }
    kept.push(fresh);
  });

  kept.sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));

  // 5. Report.
  for (const w of warnings) console.warn(`warning: ${w}`);
  for (const d of dropped) console.warn(`${checkOnly ? 'problem' : 'dropped'}: ${d.label}: ${d.reason}`);
  if (checkOnly) {
    // The script writes entries in plain code-point order of slug.
    const slugs = entries.map((e) => String(e.slug));
    if (slugs.some((s, i) => i > 0 && slugs[i - 1] >= s)) problems.push('entries are not sorted by slug');
    for (const p of problems) console.error(`problem: ${p}`);
  }

  const counts = new Map<string, number>();
  for (const c of kept) counts.set(c.category, (counts.get(c.category) ?? 0) + 1);
  console.log('\nPer category:');
  for (const cat of CATEGORIES) console.log(`  ${cat.padEnd(22)} ${counts.get(cat) ?? 0}`);
  console.log(
    `\n${kept.length} valid, ${dropped.length} ${checkOnly ? 'invalid' : 'dropped'}, ${warnings.length} warnings` +
      (checkOnly ? `, ${problems.length + dropped.length} problems` : '')
  );

  if (checkOnly) {
    if (problems.length + dropped.length > 0) process.exit(1);
    console.log('OK: data/compounds.json is valid.');
    return;
  }

  const output = { _comment: COMMENT, compounds: kept };
  writeFileSync(DATA_PATH, JSON.stringify(output, null, 2) + '\n');
  console.log(`Wrote ${kept.length} compounds to ${DATA_PATH}`);

  // Slim slug <-> CID map for the app bundle (the full dataset is ~500 KB).
  writeFileSync(SLUGS_PATH, JSON.stringify(compoundSlugMap(kept), null, 2) + '\n');
  console.log(`Wrote ${SLUGS_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
