/**
 * Validate and refresh the curated structure lists in data/.
 *
 *   data/popularPdbs.json  PDB entries used for the sitemap and landing pages
 *   data/alphafold.json    UniProt accessions that have an AlphaFold DB model
 *   data/collections.json  topic collections that reference the two lists above
 *
 * Usage:
 *   pnpm exec tsx scripts/validate-ids.ts           fix mode: refresh and write the files
 *   pnpm exec tsx scripts/validate-ids.ts --check   check mode: never writes, exits 1 on any problem
 *
 * What it does:
 *   - PDB: every id is looked up at https://data.rcsb.org/rest/v1/core/entry/{ID}.
 *     A 404 (obsolete or unknown entry) is dropped with a warning in fix mode and is an
 *     error in check mode. `title` is RCSB struct.title as returned, `revised` is the
 *     latest revision date (falling back to the initial release date).
 *   - AlphaFold: every accession must return a non-empty list from
 *     https://alphafold.ebi.ac.uk/api/prediction/{ID}. name/gene/organism come from the
 *     UniProt REST API, with the AlphaFold record as a fallback. `revised` is the AF
 *     modelCreatedDate when present.
 *   - Both lists are de-duplicated and sorted by id, then written with 2-space indentation.
 *   - Collections: every `pdb` item must be in popularPdbs.json and every `af` item in
 *     alphafold.json. Dangling items are listed and the script exits 1 (they are never
 *     removed automatically). Slugs, labels and the featured set are sanity-checked too.
 *
 * In check mode, metadata that merely drifted (for example RCSB published a new revision
 * date) is reported as a warning, not an error. Run fix mode to refresh it.
 *
 * Requests are rate-limited (6 at a time) and retried on 429/5xx; see scripts/lib/http.ts.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { HttpError, fetchJson, mapLimit } from './lib/http';

// ---------- types ----------

interface PdbEntry {
  id: string;
  title: string;
  revised: string;
  /** First experimental method, e.g. "X-RAY DIFFRACTION" (used on social cards). */
  method?: string;
  /** Best resolution in Angstrom, when applicable. */
  resolution?: number;
}

interface PdbFile {
  _comment?: string;
  pdbs: Array<PdbEntry | string>;
}

interface AfEntry {
  id: string;
  name: string;
  gene?: string;
  organism: string;
  revised?: string;
  /** AlphaFold confidence summary (used on social cards). */
  plddt?: { mean: number; veryHigh: number; confident: number; low: number; veryLow: number };
}

interface AfFile {
  _comment?: string;
  entries: Array<AfEntry | string>;
}

interface CollectionItem {
  type: 'pdb' | 'af';
  id: string;
  label: string;
  note?: string;
}

interface Collection {
  slug: string;
  title: string;
  intro: string;
  featured: boolean;
  items: CollectionItem[];
}

interface CollectionsFile {
  _comment?: string;
  collections: Collection[];
}

// ---------- setup ----------

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PDB_PATH = resolve(ROOT, 'data/popularPdbs.json');
const AF_PATH = resolve(ROOT, 'data/alphafold.json');
const COLLECTIONS_PATH = resolve(ROOT, 'data/collections.json');

const CHECK = process.argv.includes('--check');
const CONCURRENCY = 6;
const EXPECTED_FEATURED = 8;

const PDB_COMMENT =
  "Generated by scripts/validate-ids.ts. Edit the 'pdbs' ids, then re-run the script.";
const AF_COMMENT =
  "Generated by scripts/validate-ids.ts. Edit the 'entries' ids (UniProt accessions with an AlphaFold DB model), then re-run the script.";

const PDB_ID_RE = /^[0-9][A-Z0-9]{3}$/;
// UniProt accession format, see https://www.uniprot.org/help/accession_numbers
const UNIPROT_RE = /^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})$/;
const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const EM_DASH = String.fromCharCode(0x2014);

const errors: string[] = [];
const warnings: string[] = [];
const error = (msg: string) => errors.push(msg);
const warn = (msg: string) => warnings.push(msg);

const readJson = async <T>(path: string): Promise<T> =>
  JSON.parse(await readFile(path, 'utf8')) as T;

const writeJson = (path: string, data: unknown) =>
  writeFile(path, JSON.stringify(data, null, 2) + '\n', 'utf8');

const day = (iso: string | undefined): string | undefined => iso?.slice(0, 10);

const byId = (a: { id: string }, b: { id: string }) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

/** Normalize a list that may contain bare id strings, report duplicates and bad ids. */
function normalizeIds<T extends { id: string }>(
  raw: Array<T | string>,
  label: string,
  format: RegExp,
  upper: boolean
): { ids: string[]; previous: Map<string, T> } {
  const previous = new Map<string, T>();
  const ids: string[] = [];
  const seen = new Set<string>();
  for (const item of raw) {
    const rawId = typeof item === 'string' ? item : item.id;
    const id = upper ? rawId.trim().toUpperCase() : rawId.trim();
    if (!format.test(id)) {
      error(`${label}: "${rawId}" is not a valid id`);
      continue;
    }
    if (seen.has(id)) {
      (CHECK ? error : warn)(`${label}: duplicate id ${id}${CHECK ? '' : ' (removed)'}`);
      continue;
    }
    seen.add(id);
    ids.push(id);
    if (typeof item !== 'string') previous.set(id, item);
  }
  if (CHECK) {
    const sorted = [...ids].sort();
    if (ids.some((id, i) => id !== sorted[i])) error(`${label}: ids are not sorted`);
  }
  return { ids, previous };
}

// ---------- PDB ----------

interface RcsbEntry {
  struct?: { title?: string };
  rcsb_accession_info?: { revision_date?: string; initial_release_date?: string };
  exptl?: Array<{ method?: string }>;
  rcsb_entry_info?: { resolution_combined?: number[] };
}

async function fetchPdb(id: string): Promise<PdbEntry | null> {
  try {
    const data = await fetchJson<RcsbEntry>(`https://data.rcsb.org/rest/v1/core/entry/${id}`);
    const info = data.rcsb_accession_info ?? {};
    const method = data.exptl?.[0]?.method;
    const resolution = data.rcsb_entry_info?.resolution_combined?.[0];
    return {
      id,
      title: data.struct?.title ?? '',
      revised: day(info.revision_date ?? info.initial_release_date) ?? '',
      ...(method ? { method } : {}),
      ...(typeof resolution === 'number' ? { resolution: Math.round(resolution * 100) / 100 } : {}),
    };
  } catch (err) {
    if (err instanceof HttpError && err.status === 404) return null;
    throw err;
  }
}

async function validatePdbs(): Promise<{ file: PdbFile; entries: PdbEntry[] }> {
  const file = await readJson<PdbFile>(PDB_PATH);
  const { ids, previous } = normalizeIds<PdbEntry>(file.pdbs ?? [], 'popularPdbs', PDB_ID_RE, true);
  console.log(`PDB: checking ${ids.length} entries...`);

  const fetched = await mapLimit(ids, CONCURRENCY, fetchPdb);
  const entries: PdbEntry[] = [];
  let drift = 0;
  fetched.forEach((entry, i) => {
    const id = ids[i];
    if (!entry) {
      (CHECK ? error : warn)(
        `popularPdbs: ${id} not found at RCSB (obsolete or unknown)${CHECK ? '' : ', dropped'}`
      );
      return;
    }
    if (!entry.title) error(`popularPdbs: ${id} has no title at RCSB`);
    const old = previous.get(id);
    if (!old || old.title !== entry.title || old.revised !== entry.revised) drift++;
    entries.push(entry);
  });
  if (CHECK && drift > 0) {
    warn(`popularPdbs: ${drift} entries have missing or outdated title/revised (run without --check)`);
  }
  entries.sort(byId);
  return { file, entries };
}

// ---------- AlphaFold ----------

interface AfPrediction {
  modelEntityId?: string;
  modelCreatedDate?: string;
  uniprotAccession?: string;
  uniprotDescription?: string;
  gene?: string;
  organismScientificName?: string;
  globalMetricValue?: number;
  fractionPlddtVeryHigh?: number;
  fractionPlddtConfident?: number;
  fractionPlddtLow?: number;
  fractionPlddtVeryLow?: number;
}

interface UniProtRecord {
  proteinDescription?: {
    recommendedName?: { fullName?: { value?: string } };
    submissionNames?: Array<{ fullName?: { value?: string } }>;
  };
  genes?: Array<{ geneName?: { value?: string } }>;
  organism?: { scientificName?: string };
}

async function fetchUniProt(id: string): Promise<UniProtRecord | null> {
  try {
    return await fetchJson<UniProtRecord>(
      `https://rest.uniprot.org/uniprotkb/${id}.json?fields=protein_name,gene_names,organism_name`
    );
  } catch (err) {
    if (err instanceof HttpError) return null;
    throw err;
  }
}

async function fetchAf(id: string): Promise<AfEntry | null> {
  let predictions: AfPrediction[];
  try {
    predictions = await fetchJson<AfPrediction[]>(`https://alphafold.ebi.ac.uk/api/prediction/${id}`);
  } catch (err) {
    if (err instanceof HttpError && (err.status === 404 || err.status === 422)) return null;
    throw err;
  }
  if (!Array.isArray(predictions) || predictions.length === 0) return null;
  const model = predictions.find((p) => p.modelEntityId === `AF-${id}-F1`) ?? predictions[0];

  const uniprot = await fetchUniProt(id);
  const desc = uniprot?.proteinDescription;
  const name =
    desc?.recommendedName?.fullName?.value ??
    desc?.submissionNames?.[0]?.fullName?.value ??
    model.uniprotDescription ??
    '';
  const gene = uniprot?.genes?.[0]?.geneName?.value ?? model.gene;
  const organism = uniprot?.organism?.scientificName ?? model.organismScientificName ?? '';

  const revised = day(model.modelCreatedDate);
  const round = (x: number) => Math.round(x * 1000) / 1000;
  const plddt =
    typeof model.globalMetricValue === 'number' && typeof model.fractionPlddtVeryHigh === 'number'
      ? {
          mean: Math.round(model.globalMetricValue * 10) / 10,
          veryHigh: round(model.fractionPlddtVeryHigh),
          confident: round(model.fractionPlddtConfident ?? 0),
          low: round(model.fractionPlddtLow ?? 0),
          veryLow: round(model.fractionPlddtVeryLow ?? 0),
        }
      : undefined;
  // Build in a fixed key order so the output file diffs cleanly.
  return {
    id,
    name,
    ...(gene ? { gene } : {}),
    organism,
    ...(revised ? { revised } : {}),
    ...(plddt ? { plddt } : {}),
  };
}

async function validateAf(): Promise<{ file: AfFile; entries: AfEntry[] }> {
  const file = await readJson<AfFile>(AF_PATH);
  const { ids, previous } = normalizeIds<AfEntry>(file.entries ?? [], 'alphafold', UNIPROT_RE, true);
  console.log(`AlphaFold: checking ${ids.length} entries...`);

  const fetched = await mapLimit(ids, CONCURRENCY, fetchAf);
  const entries: AfEntry[] = [];
  let drift = 0;
  fetched.forEach((entry, i) => {
    const id = ids[i];
    if (!entry) {
      (CHECK ? error : warn)(
        `alphafold: ${id} has no AlphaFold DB model${CHECK ? '' : ', dropped'}`
      );
      return;
    }
    if (!entry.name) error(`alphafold: ${id} has no protein name`);
    const old = previous.get(id);
    if (!old || JSON.stringify(old) !== JSON.stringify(entry)) drift++;
    entries.push(entry);
  });
  if (CHECK && drift > 0) {
    warn(`alphafold: ${drift} entries have missing or outdated fields (run without --check)`);
  }
  entries.sort(byId);
  return { file, entries };
}

// ---------- collections ----------

function validateCollections(
  data: CollectionsFile,
  pdbIds: Set<string>,
  afIds: Set<string>
): string[] {
  const dangling: string[] = [];
  const slugs = new Set<string>();
  const featured: string[] = [];

  for (const col of data.collections ?? []) {
    const where = `collections[${col.slug}]`;
    if (!SLUG_RE.test(col.slug)) error(`${where}: slug is not kebab-case`);
    if (slugs.has(col.slug)) error(`${where}: duplicate slug`);
    slugs.add(col.slug);
    if (!col.title?.trim()) error(`${where}: missing title`);
    if (!col.intro?.trim()) error(`${where}: missing intro`);
    if (/<[a-z/][^>]*>/i.test(col.intro ?? '')) error(`${where}: intro must be plain text`);
    if (col.featured) featured.push(col.slug);
    if (!Array.isArray(col.items) || col.items.length === 0) {
      error(`${where}: has no items`);
      continue;
    }

    const seen = new Set<string>();
    for (const item of col.items) {
      const key = `${item.type}:${item.id}`;
      if (seen.has(key)) error(`${where}: duplicate item ${key}`);
      seen.add(key);
      if (!item.label?.trim()) error(`${where}: ${key} has no label`);
      if (item.type === 'pdb') {
        if (!pdbIds.has(item.id)) dangling.push(`${col.slug}: pdb ${item.id} (${item.label})`);
      } else if (item.type === 'af') {
        if (!afIds.has(item.id)) dangling.push(`${col.slug}: af ${item.id} (${item.label})`);
      } else {
        error(`${where}: unknown item type "${(item as { type: string }).type}"`);
      }
    }
  }

  if (featured.length !== EXPECTED_FEATURED) {
    error(`collections: ${featured.length} featured collections, expected ${EXPECTED_FEATURED}`);
  }
  const firstEight = (data.collections ?? []).slice(0, EXPECTED_FEATURED).map((c) => c.slug);
  if (featured.join() !== firstEight.join()) {
    warn('collections: featured collections are not the first entries in the file');
  }
  return dangling;
}

// ---------- main ----------

async function main() {
  console.log(CHECK ? 'Mode: --check (read only)' : 'Mode: fix (files will be rewritten)');

  const [pdb, af, collections] = await Promise.all([
    validatePdbs(),
    validateAf(),
    readJson<CollectionsFile>(COLLECTIONS_PATH),
  ]);

  for (const [path, text] of [
    [PDB_PATH, JSON.stringify(pdb.entries)],
    [AF_PATH, JSON.stringify(af.entries)],
    [COLLECTIONS_PATH, JSON.stringify(collections)],
  ] as const) {
    if (text.includes(EM_DASH)) error(`${path}: contains an em-dash (U+2014)`);
  }

  const dangling = validateCollections(
    collections,
    new Set(pdb.entries.map((e) => e.id)),
    new Set(af.entries.map((e) => e.id))
  );
  for (const d of dangling) error(`dangling collection item -> ${d}`);

  if (!CHECK) {
    await writeJson(PDB_PATH, { _comment: pdb.file._comment ?? PDB_COMMENT, pdbs: pdb.entries });
    await writeJson(AF_PATH, { _comment: af.file._comment ?? AF_COMMENT, entries: af.entries });
    console.log(`Wrote ${pdb.entries.length} PDB entries and ${af.entries.length} AlphaFold entries.`);
  }

  const itemCount = collections.collections.reduce((n, c) => n + c.items.length, 0);
  console.log(
    `Summary: ${pdb.entries.length} PDB, ${af.entries.length} AlphaFold, ` +
      `${collections.collections.length} collections with ${itemCount} items.`
  );
  for (const w of warnings) console.warn(`WARN  ${w}`);
  for (const e of errors) console.error(`ERROR ${e}`);

  if (errors.length > 0) {
    console.error(`Failed with ${errors.length} error(s).`);
    process.exit(1);
  }
  console.log('OK');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
